### ISSUE TITLE
Inconsistent fonts on different machines 

### ISSUE THREAD

**Issue by Z3nAg3ncy** [umbraco/Umbraco.Uno.Issues#21] opened 2020-08-26 11:12 UTC
<img width="1680" alt="Screenshot 2020-08-26 at 12 16 30" src="https://user-images.githubusercontent.com/30283113/91297433-3b0c6480-e796-11ea-8729-e2bc2d9518e7.png">

<img width="1680" src="https://user-images.githubusercontent.com/30283113/91297614-8757a480-e796-11ea-907d-cc36d4edc04a.PNG">

this issue is that there are completely different fonts showing on different machines throughout the site so there is not one single selected font consistently showing even though the imbed font is selected 

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

**Comment by Z3nAg3ncy** [comment] 2020-08-26 15:15
the examples above ar of the main embedded font being helvetica

**Comment by limpa123** [comment] 2020-08-26 16:22
Hi @Z3nAg3ncy could share what you have entered under **Embed Font,** **Body Font** and **Heading Font** in the Theme node

**Comment by Z3nAg3ncy** [comment] 2020-08-26 16:26
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Helvetica:300,300italic,italic,600,600italic,700,700italic,800,800italic|Open+Sans:300,300italic,italic,600,600italic,700,700italic,800,800italic">

**Comment by Z3nAg3ncy** [comment] 2020-08-26 16:27
> Hi @Z3nAg3ncy could share what you have entered under **Embed Font,** **Body Font** and **Heading Font** in the Theme node

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Helvetica:300,300italic,italic,600,600italic,700,700italic,800,800italic|Open+Sans:300,300italic,italic,600,600italic,700,700italic,800,800italic">

**Comment by Z3nAg3ncy** [comment] 2020-08-26 16:33
I have updated github with the code a rexr file and an image of what we have in our inbeded font Managing DirectorThe Zen Agency07973 814 7290141 229 1333
-------- Original message --------From: limpa123 <notifications@github.com> Date: 26/08/2020  17:23  (GMT+00:00) To: "umbraco/Umbraco.Uno.Issues" <Umbraco.Uno.Issues@noreply.github.com> Cc: Z3nAg3ncy <alanronald@thezenagency.com>, Mention <mention@noreply.github.com> Subject: Re: [umbraco/Umbraco.Uno.Issues] Inconsistent fonts on different machines  (#21) 
Hi @Z3nAg3ncy could share what you have entered under Embed Font, Body Font and Heading Font in the Theme node

**Comment by Z3nAg3ncy** [comment] 2020-08-26 16:44
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Helvetica:300,300italic,italic,600,600italic,700,700italic,800,800italic|Open+Sans:300,300italic,italic,600,600italic,700,700italic,800,800italic">

**Comment by limpa123** [comment] 2020-08-26 16:57
From what I can see you are trying to get Helvetica from Google Fonts. But this font is not available there. You could use something similar from Google Fonts like **Open Sans** or **Roboto**. 

If you would like to use system fonts with proper fallbacks (Helvetica not available on all machines) you could enter this in the body and heading font like so

`"Helvetica Neue", Helvetica, Arial, sans-serif`

If you have purchased the Helvetica font there should be information included on how to install.

**Comment by Z3nAg3ncy** [comment] 2020-08-27 07:21
![open sans in theme](https://user-images.githubusercontent.com/30283113/91409827-e7555600-e83d-11ea-8f78-8201297e0807.PNG)
![open sans front end not working](https://user-images.githubusercontent.com/30283113/91410076-3d29fe00-e83e-11ea-8ca6-ff8415fe1236.PNG)
we updated the font to open sans and this does not effect the front end as attached - font still inconsistent fonts

**Comment by limpa123** [comment] 2020-08-27 08:23
Try this:
Embed Font:
`<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">`

Heading Font, Body Font:
`'Open Sans', sans-serif`

**Comment by nul800sebastiaan** [comment] 2020-08-27 08:26
I think at the moment the problem is that you can't specify fonts with spaces in them: https://github.com/umbraco/Umbraco.Uno.Issues/issues/2

**Comment by Z3nAg3ncy** [comment] 2020-08-27 08:32
this now appears to be working thanks

**Comment by nul800sebastiaan** [comment] 2020-08-27 09:33
This seems to be resolved, so I'll close this issue!

**Closed by nul800sebastiaan** 2020-08-27 09:33 UTC
